# GET
GET http://localhost:3000/events

################################
GET http://localhost:3000/clubs/4
################################
GET http://localhost:3000/clubs

################################
GET http://localhost:3000/bewertungen

### CREATE
###
# Create Event
POST http://localhost:3000/events
Content-Type: application/json

{
    "title": "Test Event - Loco",
    "description": "Happyhour",
    "time": "19:00",
    "date": "06.11.2021",
    "lokalId": 5,
    "music": "Pop"
}
###

#Create Bewertung
POST http://localhost:3000/bewertung
Content-Type: application/json

{
    "stars": 3,
    "description": "Test Bewertung",
    "lokal_id": 2
}
###

###
# Create Club
POST http://localhost:3000/clubs
Content-Type: application/json

{
    "address":"TEST", 
    "website":"TEST", 
    "music":"TEST", 
    "phoneNumber":"0123456789", 
    "price":"$$$", 
    "name":"TElST", 
    "openingHours":"12:00 - 06:00"
}

### UPDATE
PATCH http://localhost:3000/events/2
Content-Type: application/json

{
    "title": "Test Event - Loco",
    "description": "Happyhour",
    "time": "20:00",
    "date": "06.11.2021",
    "lokal_id": 5,
    "music": "POP"
}
###
#NEIN
PATCH http://localhost:3000/clubs/11
Content-Type: application/json

{
    "address":"OK", 
    "website":"TEST", 
    "music":"TEST", 
    "phone_number":"0123456789", 
    "price":"$$$", 
    "name":"TEST", 
    "opening_hours":"12:00 - 06:00"
}


### -- DELETE
DELETE http://localhost:3000/events/2
###
DELETE http://localhost:3000/clubs/10
